export const CMD = {
  getConfig: "get_config",
  saveConfig: "save_config",
  getWidgets: "get_widgets",
  getWidgetSource: "get_widget_source",
  openWidgets: "open_widgets",
  getWorkspaces: "get_workspaces",
  getActiveWorkspace: "get_active_workspace",
  switchWorkspace: "switch_workspace",
  moveWindowToDesktop: "move_window_to_desktop",
  createDesktop: "create_desktop",
  deleteDesktop: "delete_desktop",
  renameDesktop: "rename_desktop",
  togglePinWindow: "toggle_pin_window",
  showWorkspaceContextMenu: "show_workspace_context_menu",
  showDialog: "show_dialog",
  getDialogData: "get_dialog_data",
  getVolume: "get_volume",
  setVolume: "set_volume",
  setMuted: "set_muted",
  openVolumePopup: "open_volume_popup",
  openCalendar: "open_calendar",
  openWidgetConfig: "open_widget_config",
  getBatteryStatus: "get_battery_status",
  getSystemStats: "get_system_stats",
  openShutdownPopup: "open_shutdown_popup",
  toggleWifi: "toggle_wifi",
  toggleBluetooth: "toggle_bluetooth",
  toggleDarkMode: "toggle_dark_mode",
  toggleFocusAssist: "toggle_focus_assist",
  toggleAirplane: "toggle_airplane",
  toggleNightLight: "toggle_night_light",
  getQuickToggleStatus: "get_quick_toggle_status",
  getEvents: "get_events",
  addEvent: "add_event",
  updateEvent: "update_event",
  deleteEvent: "delete_event",
  syncEvents: "sync_events",
} as const;

export type CommandName = (typeof CMD)[keyof typeof CMD];
