export const WIN_GLYPHS: Record<string, string> = {
  settings: "\uE713",
  search: "\uE721",
  close: "\uE894",
  cancel: "\uE894",
  restart: "\uE72C",
  refresh: "\uE72C",
  power: "\uE7E8",
  clock: "\uE823",
  volume: "\uE995",
  "volume-1": "\uE993",
  "volume-2": "\uE994",
  "volume-x": "\uE74F",
  battery: "\uE83F",
  "battery-charging": "\uE85D",
  "battery-full": "\uE849",
  "battery-low": "\uE840",
  "battery-medium": "\uE845",
  "battery-warning": "\uE83F",
  music: "\uE8D6",
  "now-playing": "\uE8D6",
  weather: "\uE9FC",
  activity: "\uECAF",
  "alarm-clock": "\uE823",
  plus: "\uE710",
  "plus-circle": "\uE710",
  pencil: "\uE70F",
  edit: "\uE70F",
  trash: "\uE74D",
  "trash-2": "\uE74D",
  delete: "\uE74D",
  list: "\uE8FD",
  "list-bullet": "\uE8FD",
  events: "\uE787",
  calendar: "\uE787",
  "calendar-search": "\uE787",
};

export const DEFAULT_WIN_GLYPH = "\u25A0";
